name: Queued SPI NeoPixel CI

on: [pull_request, push, repository_dispatch]

jobs:
  verify:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: library
    
    steps:
    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
      with:
        python-version: '3.11'
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        fetch-depth: 2
        path: library
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
         repository: crabel99/SimIOFramework
         ref: 76492a7993f63a2c4687fcdeb5a57853a2272598
         path: framework
         submodules: recursive

    - name: Install PlatformIO
      run: |
        python -m pip install platformio==6.1.19 clang-format==18.1.8
        sudo apt-get update
        sudo apt-get install --yes doxygen graphviz

    - name: Verify native and SAMD builds
      run: python extras/ci/run.py --framework ../framework

    - name: Check patch formatting
      run: git diff --check HEAD~1
